@startuml

!define AWSPUML https://raw.githubusercontent.com/milo-minderbinder/AWS-PlantUML/release/18-2-22/dist

!includeurl AWSPUML/common.puml
!includeurl AWSPUML/ApplicationServices/AmazonAPIGateway/AmazonAPIGateway.puml
!includeurl AWSPUML/Compute/AWSLambda/AWSLambda.puml
!includeurl AWSPUML/Compute/AWSLambda/LambdaFunction/LambdaFunction.puml
!includeurl AWSPUML/Database/AmazonDynamoDB/AmazonDynamoDB.puml
!includeurl AWSPUML/Database/AmazonDynamoDB/table/table.puml
!includeurl AWSPUML/General/AWScloud/AWScloud.puml
!includeurl AWSPUML/General/client/client.puml
!includeurl AWSPUML/General/user/user.puml
!includeurl AWSPUML/General/AWSManagementConsole/AWSManagementConsole.puml
!includeurl AWSPUML/NetworkingContentDelivery/AmazonVPC/AmazonVPC.puml
!includeurl AWSPUML/SDKs/JavaScript/JavaScript.puml
!includeurl AWSPUML/Storage/AmazonS3/AmazonS3.puml
!includeurl AWSPUML/Storage/AmazonS3/bucket/bucket.puml

skinparam componentArrowColor Black
skinparam componentBackgroundColor White
skinparam nodeBackgroundColor White
skinparam agentBackgroundColor White
skinparam artifactBackgroundColor White

skinparam rectangle<<AWScloud>> {
    BackgroundColor transparent
    BorderColor darkgray
    shadowing false
}

title AWS Multiple Account strategy

USER(user, "IAM User")
AWSMANAGEMENTCONSOLE(console)

AWSCLOUD(aws_billing, "Billing Account", rectangle)
AWSCLOUD(aws_iam, "IAM Account", rectangle)

AWSCLOUD(aws_dmz, "DMZ Account", rectangle)

rectangle "Services Accounts" {
    AWSCLOUD(aws_prd, "Production Account", rectangle)
    AWSCLOUD(aws_stg, "Staging Account", rectangle)
    AWSCLOUD(aws_dev, "Development Account", rectangle)
}

AWSCLOUD(aws_log, "Logging Account", rectangle)

user -> console : Login into Aws Management Console
console -down-> aws_iam : Login into IAM Account
aws_iam -down-> aws_billing : Assume with billing administrator role
aws_iam -down-> aws_dmz : Assume with dmz administrator role
aws_iam -down-> aws_prd : Assume with prd administrator role
aws_iam -down-> aws_stg : Assume with stg administrator role
aws_iam -down-> aws_dev : Assume with dev administrator role
aws_iam -down-> aws_log : Assume with log administrator role

@enduml

@starturl

title "test Second diagram"
@enduml
