@startuml

!define COMMON https://raw.githubusercontent.com/anthunt/aws-cli-samples/master/plantuml/common.puml
!includeurl COMMON

AWSCLOUD(aws, "Network Account", rectangle) {

  AMAZONVPC(vpc_prd, "Production VPC", rectangle) {
  
  }
  
}

@enduml
