@startuml

!define COMMON https://raw.githubusercontent.com/anthunt/aws-cli-samples/master/plantuml/common.puml
!includeurl COMMON

title AWS Multiple Account strategy

USER(user, "IAM User")
AWSMANAGEMENTCONSOLE(console)

AWSCLOUD(aws_billing, "Billing Account", rectangle)
AWSCLOUD(aws_iam, "IAM Account", rectangle)

AWSCLOUD(aws_dmz, "DMZ Account", rectangle)

rectangle "Services Accounts" {
    AWSCLOUD(aws_prd, "Production Account", rectangle)
    AWSCLOUD(aws_stg, "Staging Account", rectangle)
    AWSCLOUD(aws_dev, "Development Account", rectangle)
}

AWSCLOUD(aws_log, "Logging Account", rectangle)

user -> console : Login into Aws Management Console
console -down-> aws_iam : Login into IAM Account
aws_iam -down-> aws_billing : Assume with billing administrator role
aws_iam -down-> aws_dmz : Assume with dmz administrator role
aws_iam -down-> aws_prd : Assume with prd administrator role
aws_iam -down-> aws_stg : Assume with stg administrator role
aws_iam -down-> aws_dev : Assume with dev administrator role
aws_iam -down-> aws_log : Assume with log administrator role

@enduml
