@startuml

!define COMMON https://raw.githubusercontent.com/anthunt/aws-cli-samples/master/plantuml/common.puml
!includeurl COMMON

AWSCLOUD(aws_network, "Network Account", rectangle) {

  AMAZONVPC(vpc_prd, "Production VPC", rectangle) {
  
    rectangle "Public Subnet" {
      AWSCLOUD(aws_prd_public, "Production Account", rectangle) {
        AMAZONEC2(ec2_bastion)
      }
    }
    
    rectangle "Private Subnet" {
      AWSCLOUD(aws_prd_private, "Production Account", rectangle) {
         AMAZONEC2(ec2_was)
      }
    }
    
  }
  
}

@enduml
